version: "3"

services:
  chip.api:
    build: .
    command: sh -c "uvicorn main:app --reload --port=8081 --host=0.0.0.0"  # Corrected command
    ports:
      - 6006:8080 #http
      - 6066:8081 #https
