version: '3.4'

services:
  catalogdb:
    image: postgres

  # basketdb:
  #   image: postgres
  
  distributedcache:
    image: redis

  orderdb:
    image: mcr.microsoft.com/mssql/server

  financedb:
    image: postgres
  
  trackingdb:
    image: postgres

  jobschedulerdb:
    image: mcr.microsoft.com/mssql/server

  messagebroker:
    image: rabbitmq:management

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile

  # basket.api:
  #   image: ${DOCKER_REGISTRY-}basketapi
  #   build:
  #     context: .
  #     dockerfile: Services/Basket/Basket.API/Dockerfile

  # discount.grpc:
  #   image: ${DOCKER_REGISTRY-}discountgrpc
  #   build:
  #     context: .
  #     dockerfile: Services/Discount/Discount.Grpc/Dockerfile

  ordering.api:
    image: ${DOCKER_REGISTRY-}orderingapi
    build:
      context: .
      dockerfile: Services/Ordering/Ordering.API/Dockerfile

  finance.api:
    image: ${DOCKER_REGISTRY-}financeapi
    build:
      context: .
      dockerfile: Services/Finance/Finance.API/Dockerfile

  jobscheduler.api:
    image: ${DOCKER_REGISTRY-}jobschedulerapi
    build:
      context: .
      dockerfile: Services/JobScheduler/JobScheduler.API/Dockerfile

  feedback.api:
    image: ${DOCKER_REGISTRY-}feedbackapi
    build:
      context: .
      dockerfile: Services/Feedback/Feedback.API/Dockerfile

volumes:
  postgres_catalog:
  postgres_finance:
  postgres_tracking:
  # postgres_basket:  





