version: '3.4'

#contanarise all services
services:
  catalogdb:
    image: postgres

  distributedcache:
    image: redis

  orderdb:
    image: mcr.microsoft.com/mssql/server

  financedb:
    image: postgres

  # trackingdb:
  #   image: postgres

  shippingdb:
    image: postgres

  jobschedulerdb:
    image: mcr.microsoft.com/mssql/server

  feedbackdb:
    image: postgres

  messagebroker:
    image: rabbitmq:management

  catalog.api:
    image: boonyew/csc2102_mini_project:catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile

  ordering.api:
    image: boonyew/csc2102_mini_project:orderingapi
    build:
      context: .
      dockerfile: Services/Ordering/Ordering.API/Dockerfile

  finance.api:
    image: boonyew/csc2102_mini_project:financeapi
    build:
      context: .
      dockerfile: Services/Finance/Finance.API/Dockerfile

  jobscheduler.api:
    image: boonyew/csc2102_mini_project:jobschedulerapi
    build:
      context: .
      dockerfile: Services/JobScheduler/JobScheduler.API/Dockerfile

  feedback.api:
    image: boonyew/csc2102_mini_project:feedbackapi
    build:
      context: .
      dockerfile: Services/Feedback/Feedback.API/Dockerfile

  shipping.api:
    image: boonyew/csc2102_mini_project:shippingapi
    build:
      context: .
      dockerfile: Services/Shipping/Shipping.API/Dockerfile

volumes:
  postgres_catalog:
  postgres_finance:
  postgres_tracking:
  postgres_feedback:


