name: .NET Backend with Node.js Frontend

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: change to src
      run: ls -al

    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)


    # Setup .NET for the backend
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore backend dependencies
      run: dotnet restore

    - name: Build backend
      run: dotnet build --no-restore

    - name: Test backend
      run: |
        dotnet test --no-build --verbosity normal
        
    # Setup Node.js for the frontend
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18 # Adjust if needed
        cache: 'npm'

    - name: Install frontend dependencies
      run: |
        cd frontend  # Adjust path if your frontend is in a different folder
        npm install

    - name: Build frontend
      run: |
        cd frontend
        npm run build  # Adjust if using a different build command
