name: Docker Image CI

on: push


jobs:



  build:



    runs-on: ubuntu-latest

    defaults:
        run:
          working-directory: ./src

    steps:
    - uses: actions/checkout@v4
    
    - name: install docker-compose
      run: |
            sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose
    - name: check docker-compose version
      run: docker-compose --version
            
    - name: Run docker-compose
      run: docker-compose up -d
  
